Ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import ecom_app.views
from ecom_app import views

urlpatterns = [
                  #   ADMIN URL
                  path('admin/', admin.site.urls),


                  #   APP URLS
                  path('', include('ecom_app.urls')),


                  #      libraries path
                  path('tinymce/', include('tinymce.urls')),


                  #   user Authintication
                  path('login/', views.user_login, name='handlelogin'),
                  path('signup/', views.signup, name='signup'),
                  path('',include('django.contrib.auth.urls')),


                  # profile section
                  path('user/profile/',views.profile,name='profile'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = ecom_app.views.custom_404_view

ecom_app/urls.py
from django.urls import path
from ecom_app import views
urlpatterns = [

    path('', views.index, name='index'),

    # product section
    path('product/', views.All_products, name='products'),
    path('product/<slug:slug>/', views.details, name='Product_details'),
    path('category/<int:id>/',views.category_detail,name='cat_details'),
    path('sub_cat/<int:id>/',views.product_subcategory,name='product_subcategory'), #detailview
    #ajax-filter
    path('product/filter-data/', views.filter_data, name="filter-data"),

    # order section
    path('wishlist/', views.wishlist, name='wishlist'),
    # path('my-cart/',views.my_cart,name='my-cart'),
    path('my-orders/', views.my_orders, name='my-orders'),
    path('checkout/', views.checkout, name='checkout'),

    # other pages
    path('about-us/', views.about,name='about'),
    path('contact-us/', views.contact,name='contact'),
    path('faq/', views.faq, name='faq'),

    #cart-section
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),

]

ecom_app/models.py
from django.db import models
from django.dispatch import receiver
from tinymce.models import HTMLField
from django.utils.text import slugify
from django.db.models.signals import pre_save


class Main_Category(models.Model):
    Category_name = models.CharField(max_length=50)
    cat_logo = models.ImageField(upload_to='media/Category/categoty_main/Category_logo')
    Image = models.ImageField(upload_to='media/Category/categoty_main/Category_img')

    def __str__(self):
        return self.Category_name


class Category(models.Model):
    Category_name = models.CharField(max_length=100)
    # Category_Description = models.TextField()
    Image = models.ImageField(upload_to='media/Category/Category_img')
    Main_cat = models.ForeignKey(Main_Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.Main_cat.Category_name + '---' + self.Category_name


class Sub_Category(models.Model):
    Category_name = models.CharField(max_length=100)
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.Category.Main_cat.Category_name + '-----' + self.Category.Category_name + '----  --' + self.Category_name


class Banner(models.Model):
    DISCOUNT_DEALS = (
        ('HOT DEALS', 'HOT DEALS'),
        ('NEW ARRAIVAL', 'NEW ARRAIVAL'),
    )

    Featured_cat = models.ForeignKey(Main_Category, on_delete=models.CASCADE, related_name='featuredcat')
    Discount_Offer = models.CharField(max_length=100)
    Deal = models.CharField(max_length=100, choices=DISCOUNT_DEALS)
    Discount_percent = models.IntegerField()
    Banner = models.ImageField(upload_to='media/Category/Featured_banners')

    def __str__(self):
        return self.Featured_cat.Category_name


class Section(models.Model):
    Name = models.CharField(max_length=100)

    def __str__(self):
        return self.Name


class Product(models.Model):
    Total_qty = models.IntegerField()
    Availablity = models.IntegerField()
    Featured_image = models.CharField(max_length=100)
    Product_name = models.CharField(max_length=100)
    Price = models.IntegerField()
    Discount = models.IntegerField()
    Product_Information = HTMLField()
    Model_name = models.CharField(max_length=100)
    Categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    Tags = models.CharField(max_length=100)
    Description = HTMLField()
    Section = models.ForeignKey(Section, on_delete=models.DO_NOTHING)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.Product_name

    # Creating a slug field( auto generating it from title)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('Product_details', kwargs={'slug': self.slug})

    class Meta:
        db_table = 'ecom_app_Product'


def create_slug(instance, new_slug=None):
    slug = slugify(instance.Product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


@receiver(pre_save, sender=Product)
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


class Product_image(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Image_url = models.CharField(max_length=200)


class Aditional_details(models.Model):
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Specification = models.CharField(max_length=100)
    Details = models.CharField(max_length=100)

templates/includes/footer.html
{% load static %}

   <!-- footer-start -->
    <footer>
        <div class="fotter-area d-ddark-bg">
            <div class="footer__top pt-60 pb-10">
                <div class="container 0">
                    <div class="row">
                        <div class="col-xxl-3 col-xl-4 col-lg-5 col-md-8">
                            <div class="footer__widget">
                                <div class="footer__widget-title mb-20">
                                    <h4>About The Store</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <p class="footer-text mb-25">Our mission statement is to provide the absolute best customer experience available in the Electronic industry without exception.</p>
                                    <div class="footer__hotline d-flex align-items-center mb-10">
                                        <div class="icon icon-2 mr-15">
                                            <i class="fal fa-headset"></i>
                                        </div>
                                        <div class="text text-2">
                                            <h4>Got Question? Call us 24/7!</h4>
                                            <span><a href="tel:100-123-456-7890">(+100) 123 456 7890</a></span>
                                        </div>
                                    </div>
                                    <div class="footer__info">
                                        <ul>
                                            <li>
                                                <span>Add:  <a target="_blank" href="https://goo.gl/maps/c82DDZ8ALvL878Bv8">Walls Street 68, Mahattan, New York, USA</a></span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>My Account</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="contact.html">Product Support</a></li>
                                            <li><a href="checkout.html">Checkout</a></li>
                                            <li><a href="cart.html">Shopping Cart</a></li>
                                            <li><a href="wishlist.html">Wishlist</a></li>
                                            <li><a href="faq.html">Terms &amp; Conditions &amp;</a></li>
                                            <li><a href="faq.html">Redeem Voucher</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>Customer Care</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="faq.html">New Customers</a></li>
                                            <li><a href="faq.html">How to use Account</a></li>
                                            <li><a href="faq.html">Placing an Order</a></li>
                                            <li><a href="faq.html">Payment Methods</a></li>
                                            <li><a href="faq.html">Delivery &amp; Dispatch</a></li>
                                            <li><a href="faq.html">Problems with Order</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-2 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>Customer Service</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="faq.html">Help Center</a></li>
                                            <li><a href="contact.html">Contact Us</a></li>
                                            <li><a href="faq.html">Report Abuse</a></li>
                                            <li><a href="faq.html">Submit a Dispute</a></li>
                                            <li><a href="faq.html">Policies &amp; Rules</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-3 col-xl-4 col-lg-5 col-md-6">
                            <div class="footer__widget">
                                <div class="footer__widget-title mb-20">
                                    <h4>Sign Up To Newsletter</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <p class="footer-text mb-25">Join 60.000+ subscribers and get a new discount coupon  on every Saturday.</p>
                                    <div class="footer__newsletter-form">
                                        <form action="#">
                                            <input class="ft-newsl b-radius" type="email" placeholder="Enter your email ...">
                                            <button class="ft-newsl-btn" type="submit">subscribe</button>
                                        </form>
                                        </div>
                                    <p class="provide-text mt-20">By providing your email address, you agree to our <br> <a href="#">Privacy Policy</a> and <a href="#">Terms of Service</a> .</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer__bottom-2">
                <div class="container 0">
                    <div class="footer__bottom-content footer__bottom-content-2 pt-50 pb-50">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="footer__links footer__links-d text-center mb-25">
                                    <p>
                                        <a href="about.html">About Us</a>
                                        <a href="contact.html">Delivery & Return</a>
                                        <a href="faq.html">Privacy Policy</a>
                                        <a href="faq.html">Help</a>
                                        <a href="faq.html">Order Tracking</a>
                                        <a href="contact.html">Contact Us</a>
                                        <a href="faq.html">FAQs </a>
                                    </p>
                                </div>
                                <div class="payment-image text-center mb-25">
                                    <a href="#"><img src="assets/img/payment/payment.png" alt=""></a>
                                </div>
                                <div class="copy-right-area copy-right-area-2 text-center">
                                    <p>Copyright © <span>DukaMarket.</span> All Rights Reserved. Powered by <a href="#"><span class="main-color">Theme_Pure.</span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

templates/includes/header.html
<!-- header-start -->
{% load static %}
     <header class="header d-blue-bg">
        <div class="header-top">
            <div class="container 0">
                <div class="header-inner">
                    <div class="row align-items-center">
                        <div class="col-xl-6 col-lg-7">
                            <div class="header-inner-start">

                                <div class="support d-none d-sm-block">
                                    <p>Need Help? <a href="tel:+001123456789">+001 123 456 789</a></p>
                                </div>&nbsp;&nbsp;
                                {% if user.is_authenticated %}
                                    {% if user.first_name == "" %}
                                         <div class="support d-none d-sm-block ">
                                             <p>Hello : {{ user.username }}</p></div>
                                    {% else %}
                                        {{ user.first_name }} {{ user.last_name }}

                                    {% endif %}
                                {% else %}
                                     <div class="support d-none d-sm-block">
                                    <p>User not logged in </p>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-5 d-none d-lg-block">
                            <div class="header-inner-end text-md-end">
                                <div class="ovic-menu-wrapper ovic-menu-wrapper-2">
                                    <ul>
                                        <li><a href="/">Home</a></li>
                                        <li><a href="/about-us/">About Us</a></li>
                                        <li><a href="/my-orders/">Order Tracking</a></li>
                                        <li><a href="/contact-us/">Contact Us</a></li>
                                        <li><a href="/faq/">FAQs</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-mid">
            <div class="container">
                <div class="heade-mid-inner">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                            <div class="header__info header__info-2">
                                <div class="logo logo-3">
                                    <a href="index.html" class="logo-image"><img src="{% static 'assets/img/logo/logo1.svg' %}" alt="logo"></a>
                                </div>
                                <div class="side-menu mr-20">
                                    <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                                  </div>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                            <div class="header__search">
                                <form action="#">
                                    <div class="header__search-box">
                                        <input class="search-input search-input-2" type="text" placeholder="I'm shopping for...">
                                        <button class="button button-2 button-3" type="submit"><i class="far fa-search"></i></button>
                                    </div>
                                    <div class="header__search-cat">
                                        <select>
                                            <option>All Categories</option>

                                            {% for cat in All_Main_cate %}
                                            <option><a href="/category/{{ cat.id }}">{{ cat.Category_name }}</a></option>
                                            {% endfor %}

                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-5 col-md-8 col-sm-8">
                            <div class="header-action">
                                {% if user.is_authenticated %}
                                <div class="block-userlink">
                                    <a class="icon-link icon-link-2" href="/user/profile/">
                                    <i class="flaticon-user"></i>
                                    <span class="text">
                                    <span class="sub">Manage <Profile></Profile> </span>
                                    {{ user.username}} </span>
                                    </a>
                                </div>
                                {% else %}
                                    <div class="block-userlink">
                                    <a class="icon-link icon-link-2" href="/login/">
                                    <i class="flaticon-user"></i>
                                    <span class="text">
                                    <span class="sub">Login </span>
                                    My Account </span>
                                    </a>
                                </div>
                                {% endif %}
                                <div class="block-wishlist action">
                                    <a class="icon-link icon-link-2" href="/wishlist/">
                                    <i class="flaticon-heart"></i>
                                    <span class="count count-2">0</span>
                                    <span class="text">
                                    <span class="sub">Favorite</span>
                                    My Wishlist </span>
                                    </a>
                                </div>
                            <div class="block-cart action">
                                    <a class="icon-link icon-link-2" href="/cart/cart-detail/">
                                    <i class="flaticon-shopping-bag"></i>
                                    <span class="count count-2" id="length">{{request.session.cart|length}}</span>
                                    <span class="text">
                                    <span class="sub">Your Cart:</span>
                                    ${{ cart_total_amount }}</span>
                                    </a>

                                {% include 'modals/cart_modal.html' %}
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header__bottom d-none d-lg-block">
            <div class="container">
                <div class="box-items-inner pt-10 pb-10">
                     {% for cat in All_Main_cate %}
                    <div class="box-item">
                        <a href="/category/{{ cat.id }}/">
                            <img style="height: 50px; " src="/{{ cat.cat_logo }}">
                            {{ cat.Category_name }}
                        </a>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
     </header>
     <!-- header-end -->

    <!-- //side-menu -->
    <div class="main-menu">
        <nav id="mobile-menu-2">
            <ul>
                <li>
                    <a href="/" class="active">Home <i class="far fa-angle-down"></i></a>

                </li>
                <li><a href="/about-us/">About Us</a></li>
                <li><a href="/product/">Shop <i class="far fa-angle-down"></i></a>

                    <ul class="megamenu-1">
                        {% for m in All_Main_cate %}
                            <li><a href="/category/{{ m.id }}">{{ m.Category_name}}</a>
                            <ul class="mega-item">
                                {% for c in m.category_set.all %}
                                <li><a href="index.html">{{ c.Category_name }}</a></li>
                                    {% endfor %}

                            </ul>
                        </li>
                        {% endfor %}

                    </ul>
                </li>
                <li><a href="/my-orders/">My Orders<i class="far fa-angle-down"></i></a>
                    <ul class="submenu">
                        <li><a href="/my-orders/">All Orders</a></li>
                        <li><a href="/track-orders">Track your order</a></li>
                    </ul>
                </li>
                <li>
                    <a href="about.html">More<i class="far fa-angle-down"></i></a>
                    <ul class="submenu">
                        <li><a href="/user/profile/">My Account</a></li>
                        <li><a href="/product-details/">Product Details</a></li>
                        <li><a href="/faq/">FAQs pages</a></li>
                        <li><a href="cart/cart-detail/">Cart</a></li>
                        <li><a href="/wishlist/">Wishlist</a></li>
{#                        <li><a href="/checkout/">Checkout</a></li>#}
                        <li><a href="/contact-us/">Contact Us</a></li>
{#                        <li><a href="404.html">404 Error</a></li>#}
                    </ul>
                </li>
            </ul>
        </nav>
    </div>


{# side bar#}

    <!-- offcanvas area start -->
    <div class="offcanvas__area">
        <div class="offcanvas__wrapper">
        <div class="offcanvas__close">
            <button class="offcanvas__close-btn" id="offcanvas__close-btn">
                <i class="fal fa-times"></i>
            </button>
        </div>
        <div class="offcanvas__content">
            <div class="offcanvas__logo mb-40">
                <a href="index.html">
                <img src="{% static 'assets/img/logo/logo-white.png' %}" alt="logo">
                </a>
            </div>
            <div class="offcanvas__search mb-25">
                <form action="#">
                    <input type="text" placeholder="What are you searching for?">
                    <button type="submit" ><i class="far fa-search"></i></button>
                </form>
            </div>
            <div class="sidebar__img mb-20">
                <div class="row gx-2">
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-1.jpg">
                            <img src="assets/img/gallery/gal-1.jpg" alt="">
                         </a>
                      </div>
                   </div>
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-2.jpg">
                            <img src="assets/img/gallery/gal-2.jpg" alt="">
                         </a>
                      </div>
                   </div>
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-3.jpg">
                            <img src="assets/img/gallery/gal-3.jpg" alt="">
                         </a>
                      </div>
                   </div>
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-4.jpg">
                            <img src="assets/img/gallery/gal-4.jpg" alt="">
                         </a>
                      </div>
                   </div>
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-5.jpg">
                            <img src="assets/img/gallery/gal-5.jpg" alt="">
                         </a>
                      </div>
                   </div>
                   <div class="col-4">
                      <div class="sidebar__single-img hover-effect w-img mb-10">
                         <a class="popup-image" href="assets/img/gallery/gal-6.jpg">
                            <img src="assets/img/gallery/gal-6.jpg" alt="">
                         </a>
                      </div>
                   </div>
                </div>
             </div>
            <div class="mobile-menu-2"></div>
            <div class="offcanvas__action">
            </div>
        </div>
        </div>
    </div>
    <!-- offcanvas area end -->
    <div class="body-overlay"></div>
    <!-- offcanvas area end -->